# Generated by Django 4.2.30 on 2026-06-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='mood',
            field=models.CharField(default='Neutral', max_length=20),
        ),
    ]
