# Generated by Django 4.2.30 on 2026-06-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_mood'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentalHealthResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Sad', 'Sad'), ('Anxious', 'Anxious'), ('Stress', 'Stress'), ('General', 'General')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('link_or_contact', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
