# Generated by Django 4.2.30 on 2026-06-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_mentalhealthresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentalhealthresource',
            name='category',
            field=models.CharField(choices=[('Sad', 'Sad'), ('Anxious', 'Anxious'), ('Angry', 'Angry'), ('General', 'General')], max_length=20),
        ),
    ]
